docker:
  image: node
  port: 8080
  volume: /root/app

start: npm install && node server.js

paths:
  home: /
  about: /about.html
  contact: /contact.html
  samsung: /samsung.html
  tesla: /tesla.html
  events: /events.html
